Website/Models/WishList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Website.Models
{
    public class WishList
    {
        public int Id { set; get; }
        //[ForeignKey("UerId")]
        public string ASIN { set; get; }
        public virtual ApplicationUser User { get; set; }
        //[ForeignKey("ProductId")]
        public virtual Product Product { get; set; }
        public WishList()
        {
            User = new ApplicationUser();
            Product = new Product();
        }
    }
}

Website/Controllers/WishListsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Website.Models;
using Website.Utils;

namespace Website.Controllers
{
    public class WishListsController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: WishLists
        public ActionResult Index()
        {
            var Id = User.Identity.GetUserId();
            var list = (from rec in db.WishList where rec.User.Id == Id select rec.Product.Id).ToList();

            if (list == null)
                return View(list);
            var listWish = (from rec in db.Products where list.Contains(rec.Id) select rec).ToList();
                 
            return View(listWish);
        }
         
        

        // [ValidateAntiForgeryToken]
        public ActionResult Create(int Id)
        {
            if (ModelState.IsValid)
            {
                //WishList w = db.WishList.FirstOrDefault(rec => rec.Product.Id == Id);
                //if (w == null)
                //{
                   Product p = db.Products.Find(Id);
                    //if (p == null)
                    //{
                    //    Console.WriteLine("no product in Db");
                    //    //need to call api
                    //}

                    ApplicationUser u = db.Users.Find(User.Identity.GetUserId());
                    Console.WriteLine("user id" + u.Email);

                    WishList wish = new WishList()
                    {
                        ASIN = p.ASIN,

                        Product = p,
                        
                        User = u
                    };

                    db.WishList.Add(wish);
                    db.SaveChanges();

                }

            //}

            return RedirectToAction("Index", "Product");
        }



        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            WishList wishList = db.WishList.FirstOrDefault(rec=>rec.Product.Id==id);
            wishList.Product = null;
            wishList.User = null;
            db.WishList.Remove(wishList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Action method to email
        public ActionResult sendEmail(String ToEmailList)
        {
            if (ToEmailList==null)
            {
                return View("SendEmail");
            }
            var Id = User.Identity.GetUserId();
            var list = (from rec in db.WishList where rec.User.Id == Id select rec.Product.Id).ToList();

            if (list == null)
                return View(list);
            List<Product> products = (from rec in db.Products where list.Contains(rec.Id) select rec).ToList();

            EmailClient ec = new EmailClient();
            Boolean MSGSentStatus = true;
            if (ToEmailList.Contains(","))
            {
                String[] EmailList = ToEmailList.Split(',');
                foreach(String ToEmail in EmailList)
                {
                    MSGSentStatus = MSGSentStatus && ec.sendEmail(ToEmail, products, User.Identity.GetUserName());
                }
            }
            else
            {
                MSGSentStatus = ec.sendEmail(ToEmailList, products, User.Identity.GetUserName());
            }
            if (MSGSentStatus)
            {
                return Json(new { Success = "true", Message = "Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = "false", Message = "Failure" },JsonRequestBehavior.AllowGet);
            }
            

            

        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Website/Views/WishLists/EmailConformation.cshtml
@{





    <h2>    Your WishList was sent successfully!!! </h2> //will change this


}

Website/Views/WishLists/Index.cshtml
@{
    ViewBag.Title = "Favourites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Count == 0)
{<p> No Favourites!!!</p>}

<div class="div-block"></div>
<div class="section-2 w-clearfix">
    <h3 class="heading">Maybe List</h3>
    <a href="@Url.Action("sendEmail", "Wishlists")" class="share-button w-inline-block"><img src="/images/share-100b.png" width="25" class="share-icon"></a>
</div>

@foreach (var item in Model)
{
    <div class="favorite-item">
        @Html.ActionLink("REMOVE", "Delete", "WishLists", new { id = item.Id }, htmlAttributes: new { @class = "remove_favorite w-button" })
        <img src="@item.LargeImage" width="100" class="favorite_item_image">
        <div class="favorite_product_name">@item.Title</div><a href="@item.DetailPageURL" class="shop_favorite w-button">SHOP</a>
    </div>
}

Website/Views/WishLists/SendEmail.cshtml
@{
    ViewBag.Title = "Share";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<div class="div-block"></div>
<div class="section-2  w-clearfix">
    <h3 class="heading">Share Maybe List</h3>
</div>
<div class="form-block w-form">
    
        <label for="Email-To" class="field-label-2">Send to:</label><textarea id="Email-To" name="Email-To" placeholder="Enter the recipient&#x27;s email address (separate multiple email addresses with a comma)" maxlength="5000" data-name="Email To" required="" class="textarea w-input"></textarea>
        <div class="div-block-4">
            <a href="#" id="sendmail" class="submit-button w-button">Send Now</a>
            <a href="@Url.Action("Index", "Wishlists")" class="link-2">Go Back</a></div>

  




    <!-- The Modal -->
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p id="modalmsg"></p>
        </div>

    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        // Get the modal
        var modal = document.getElementById('myModal');

        $("#sendmail").click(function () {
                var url = '/Wishlists/sendEmail?ToEmailList=' + document.getElementById("Email-To").value
                $.get(url, function (data, status) {
                    if (data.Success == 'true') {
                        document.getElementById('modalmsg').innerText = 'Maybe List Emailed successfully!!!';
                        modal.style.display = "block";
                    } else {
                        document.getElementById('modalmsg').innerText = 'Oops! Something went wrong. Please try again.';
                        modal.style.display = "block";
                    }
                });
        });

        $(".close").click(function () {
            modal.style.display = "none";
        });
        


        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>



    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 200px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 50%;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

            .close:hover,
            .close:focus {
                color: #000;
                text-decoration: none;
                cursor: pointer;
            }


    </style>




</div>

Website/Views/WishLists/WishListEmailTemplate.cshtml
<html>
<body>
    <h2>WishList</h2>
    <br />


    @foreach (var item in Model)
    {


        <div class="div-block"></div>
        <div class="favorite-item">
            <img src="@item.LargeImage" width="100" class="favorite_item_image">
            <div class="favorite_product_name">@item.Title</div><a href="@item.DetailPageURL" class="shop_favorite w-button">SHOP</a>
        </div>



    }
</body>
</html>