SampleAuth1/Controllers/ProductAdminController.cs
using SampleAuth1.DBService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SampleAuth1.Controllers
{
    public class ProductAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ProductAdmin
        public ActionResult Index()
        {
            ViewBag.Message = "This is Product Admin Page";
            return View();
        }
        public ActionResult ManageProducts()
        {

            
            return View();
        }
        public ActionResult ManageCategory()
        {
            var list = (from category in db.Categories
                                                select category).ToList();
            if (list == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(list);
            
        }

    }
}

SampleAuth1/Views/ProductAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>




@Html.ActionLink("ManageProducts", "ManageProducts", "ProductAdmin", routeValues: null, htmlAttributes: new { @class = "nav-link-6 signup w-nav-link" })
@Html.ActionLink("ManageCategory", "ManageCategory", "ProductAdmin", routeValues: null, htmlAttributes: new { @class = "nav-link-6 signup w-nav-link" })

SampleAuth1/Views/ProductAdmin/ManageCategory.cshtml
@{
    ViewBag.Title = "ManageCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManageCategory</h2>
@*@foreach(var category in Model)
{
@category.CategoryId

}*@


<table style="width:100% ;text-align:left">
        <tr>
            <th>CategoryId</th>
            <th>CategoryName</th>
        </tr>
@foreach (var category in Model)
{
        <tr>
            <td>@category.CategoryId</td>
            <td>@category.CategoryName</td>

        </tr>
}
    </table>






@Html.ActionLink("Home", "Index", "ProductAdmin", routeValues: null, htmlAttributes: new { @class = "nav-link-6 signup w-nav-link" })

SampleAuth1/Views/ProductAdmin/ManageProducts.cshtml
@{
    ViewBag.Title = "ManageProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManageProducts</h2>

<table style="width:100%;text-align:left">
    <tr>
        <th>ProductId</th>
        <th>Title</th>
        <th>Category</th>
        <th>ImageURL</th>
        <th>Details</th>
    </tr>
    <tr>
        <td>Jill</td>
        <td>Smith</td>
        <td>50</td>
        <td>Smith</td>
        <td><a href="https://www.google.com">Detail</a></td>
    </tr>
    <tr>
        <td>Eve</td>
        <td>Jackson</td>
        <td>94</td>
        <td>Smith</td>
        <td><a href="https://www.google.com">Detail</a></td>
    </tr>
    <tr>
        <td>Eve</td>
        <td>Jackson</td>
        <td>94</td>
        <td>Smith</td>
        <td><a href="https://www.google.com">Detail</a></td>
    </tr>
    <tr>
        <td>Eve</td>
        <td>Jackson</td>
        <td>94</td>
        <td>Smith</td>
        <td><a href="https://www.google.com">Detail</a></td>
    </tr>
</table>

@Html.ActionLink("Home", "Index", "ProductAdmin", routeValues: null, htmlAttributes: new { @class = "nav-link-6 signup w-nav-link" })