SampleAuth1/Models/WishList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SampleAuth1.Models
{
    public class WishList
    {
        public int Id { set; get; }
        [Required]
        public String  ApplicationUser_Id { get; set; }
        [Required]
        public int Product_Id { get; set; }
        public WishList()
        {

        }

        
    }
}

SampleAuth1/Controllers/ProductBrowseController.cs
using SampleAuth1.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SampleAuth1.DBService;
using System.Data.Entity.Validation;
using SampleAuth1.Utils;

namespace SampleAuth1.Controllers
{
    public class ProductBrowseController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: ProductBrowse/Index
        public ActionResult Index()
        {
            String ApplicationUser_Id = User.Identity.GetUserId();
            if (ApplicationUser_Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            List<Product> totalProductList = (from product in db.Products
                                              where
                                              (from uc in db.UserCategories
                                               where uc.ApplicationUser_Id == ApplicationUser_Id
                                               select uc.CategoryId).Contains(product.CategoryId)
                                              select product).ToList<Product>();
            List<Product> wishlist = getWishList();
            List<Product> scraplist = getScrapList();
            List<Product> notviewedproductlist = new List<Product>();


            foreach (Product product in wishlist)
            {
                totalProductList.Remove(product);
            }

            foreach (Product product in scraplist)
            {
                totalProductList.Remove(product);
            }

            if (totalProductList.Count == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Random random = new Random();
                int rIndex = random.Next(0, totalProductList.Count);
                var randomList = new List<Product>();

                randomList.Add(totalProductList[rIndex]);


                return View(randomList);
            }


        }

        //Adding to WishList
        public ActionResult AddToFav(int pid)
        {


            WishList wl = new WishList()
            {

                ApplicationUser_Id = User.Identity.GetUserId(),
                Product_Id = pid
            };

            db.WishLists.Add(wl);

            db.SaveChanges();


            return RedirectToAction("Index");
        }
        //Adding to scrap list
        public ActionResult notFav(int pid)
        {
            ScrapList sl = new ScrapList()
            {
                ApplicationUser_Id = User.Identity.GetUserId(),
                Product_Id = pid
            };

            db.ScrapLists.Add(sl);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: ProductBrowse/Favorites
        public ActionResult WishList()
        {
            List<Product> list = getWishList();
            if (list == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View("WishList", list);

        }

        private List<Product> getWishList()
        {
            String ApplicationUser_Id = User.Identity.GetUserId();
            var productIdList = (from wl in db.WishLists where wl.ApplicationUser_Id == ApplicationUser_Id select wl.Product_Id);
            List<Product> wishlist = (from p in db.Products where productIdList.Contains(p.Id) select p).ToList<Product>();
            return wishlist;
        }

        private List<Product> getScrapList()
        {
            String ApplicationUser_Id = User.Identity.GetUserId();
            var productIdList = (from sl in db.ScrapLists where sl.ApplicationUser_Id == ApplicationUser_Id select sl.Product_Id);
            List<Product> scraplist = (from p in db.Products where productIdList.Contains(p.Id) select p).ToList<Product>();
            return scraplist;
        }

        public ActionResult RemoveFromWishList(int pid)
        {
            WishList removeItem = (from wl in db.WishLists
                                   where wl.Product_Id == pid
                                   select wl).FirstOrDefault();


            db.WishLists.Remove(removeItem);

            db.SaveChanges();

            List<Product> list = getWishList();
            if (list == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View("WishList", list);
        }
        // Tosend email 
        public ActionResult sendEmail(String ToEmail)
        {
            EmailClient ec = new EmailClient();
            List<Product> products = getWishList();
            ec.sendEmail(ToEmail, products);
            return View("EmailConfirmation");

        }
    }
}

SampleAuth1/Views/ProductBrowse/EmailConfirmation.cshtml
@{
    ViewBag.Title = "Email Confirmation Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{

    <h2>    Your WishList was sent successfully!!!</h2>


}

SampleAuth1/Views/ProductBrowse/Index - Copy.cshtml
@{
    ViewBag.Title = "Product Browse Page";
}

<div class="text-block-2">Here is your Product Browse Page!!!</div>
<div class="div-block"></div>
<div class="add_remove">
    <a href="#" class="button_remove w-button">x</a>
    <a href="#" class="button_add w-button">+</a>
</div>@*Write a function to update in Database*@

<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval=false>



        <!-- Wrapper for slides -->
        <div class="carousel-inner">
   



            @{ 


                foreach (var item in Model)
                {
                    @*<div class="item">
                        <img src="@item.LargeImage" alt="Product">

                     </div>*@
                    
                        <div class="item active">
                      <img src="@item.LargeImage" alt="Product">
                  
                      </div>
                        
                    

                }
                }

        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

SampleAuth1/Views/ProductBrowse/Index.cshtml
@{
    ViewBag.Title = "Product Browse Page";
}

@if (Request.IsAuthenticated)
{


    foreach (var item in Model)
    {
        <div class="div-block"></div>
        <div class="add_remove">
            @Html.ActionLink("x", "notFav", "ProductBrowse", new { pid = item.Id }, htmlAttributes: new { @class = "button_remove w-button" })
            @Html.ActionLink("+", "AddToFav", "ProductBrowse", new { pid = item.Id }, htmlAttributes: new { @class = "button_add w-button" })

        </div>
        <div class="product-view w-container">
            <img src="@item.LargeImage" width="600" height="600" srcset="@item.LargeImage 500w, @item.LargeImage 600w" sizes="(max-width: 479px) 90vw, (max-width: 767px) 80vw, (max-width: 991px) 582.390625px, 600px" class="product-image"></div>
        <div class="section">
            <div class="product-name"></div>
        </div>
        <div class="product-description"></div>

    }
}

SampleAuth1/Views/ProductBrowse/WishList.cshtml
@{
    ViewBag.Title = "WishList Page";
}

@if (Request.IsAuthenticated)
{

    <div class="div-block"></div>
    <div class="sendmail-item">
        Email To:
        <input type="text" id="ToEmail" />
        
        @Html.ActionLink("Send Email", "sendEmail", "ProductBrowse", null, htmlAttributes: new { @class = "sendmail_favorite w-button" , onclick="SubmitToEmail(this)" })
    </div>

    <script>
        function SubmitToEmail(obj) {
            obj.href = obj.href + '?ToEmail='+document.getElementById("ToEmail").value;
        }
    </script>

        foreach (var item in Model)
        {


        <div class="div-block"></div>
        <div class="favorite-item">
            @Html.ActionLink("REMOVE", "RemoveFromWishList", "ProductBrowse", new { pid = item.Id }, htmlAttributes: new { @class = "remove_favorite w-button" })
            <img src="@item.LargeImage" width="100" class="favorite_item_image">
            <div class="favorite_product_name">@item.Title</div><a href="@item.DetailPageURL" class="shop_favorite w-button">SHOP</a>
        </div>



        }

        }

SampleAuth1/Views/ProductBrowse/WishListEmailTemplate.cshtml
    <html>
    <body>
        <h2>WishList</h2>
        <br />


        @foreach (var item in Model)
        {


        <div class="div-block"></div>
        <div class="favorite-item">
            <img src="@item.LargeImage" width="100" class="favorite_item_image">
            <div class="favorite_product_name">@item.Title</div><a href="@item.DetailPageURL" class="shop_favorite w-button">SHOP</a>
        </div>



        }
    </body>
</html>